#!/usr/bin/env python
import sys
import subprocess

if __name__ == "__main__":
    if len(sys.argv) == 2:
        protocol = sys.argv[1]
        f = open("/Applications/uri-handler.app/Contents/Info.plist", "r")
        contents = f.readlines()
        f.close()
        f = open("/Applications/uri-handler.app/Contents/Info.plist", "w")
        for line in contents:
            if line != "              <string>" + protocol + "</string>\n":
                f.write(line)
                
        subprocess.run("touch /Applications/uri-handler.app; rm " + protocol, shell=True)
        print("deleted handler: (" + protocol + "), and removed " + protocol + " from Info.plist file.")
    else:
        print("please provide a handler protocol name")
